dependencies:
  - pandas==1.1.3
  - fastcluster==1.1.26
  - tqdm==4.50.2
  - scipy==1.5.2
  - Cartopy==0.17.0
  - ipywidgets==7.5.1
  - numpy==1.19.2
  - matplotlib==3.3.2
  - watermark==2.1.0
  - networkx==2.5
  - scikit_learn==0.24.1
