dependencies:
  - seaborn==0.11.0
  - tqdm==4.50.2
  - networkx==2.5
  - watermark==2.1.0
  - numpy==1.19.2
  - matplotlib==3.3.2
  - Cartopy==0.18.0
  - geopy==2.1.0
  - nltk==3.5
  - fastcluster==1.1.26
  - pandas==1.1.3
  - osmnx==1.0.1
  - scipy==1.6.0
  - ipywidgets==7.5.1
  - scikit_learn==0.24.1
